### ISSUE TITLE
NullPointerException in AbstractClient

### ISSUE THREAD

**Issue by dimas** [kairosdb/kairosdb-client#34] opened 2015-03-17 17:59 UTC
```
	at org.kairosdb.client.AbstractClient.getResponse(AbstractClient.java:177)
	at org.kairosdb.client.AbstractClient.pushMetrics(AbstractClient.java:132)
```

I guess the server is either returning malformed JSON or just does not include "errors" there.
Cannot tell because the actual response is not logged.
Also have no idea how to reproduce as it happens from time to time only.

**Comment by FrEaKmAn** [comment] 2015-03-17 19:52
Can you check kairosdb or cassandra log for possible errors?

**Comment by jsabin** [comment] 2015-05-14 22:43
Can you give more information about this problem?

**Comment by dimas** [comment] 2015-05-21 10:13
No, I am sorry guys. That thing runs in a live system under a lot of requests and the issue is not something that happens every second. It is kind of difficult to collect evidences when a problem occurs because all Kairos servers are behind a load balancer so you do not know to which sevrer this particular request went and in the end you have to dig through a combined log which is huge. If I could reproduce it with a single KairosDB + single Cassandra setup I would be happy to collect all the evidences.

My point is that that kind of things like unexpected reponse from a server happens in real life so the code should be prepared for it and handle it accordingly. For example by returning a null result instead of trying to dereference null. Or better - by throwing an appropriate exception that says the resonse is malformed or status code is not something it expected. And possibly by logging some evidences - like the entire response body (but with debug level of course), status code, etc.

Cheers

**Comment by jsabin** [comment] 2015-05-26 22:35
I'm looking for a full stack trace so I can identify where the problem is.

**Comment by jsabin** [comment] 2015-07-23 22:26
I can't reproduce so I'm closing this issue.

**Closed by jsabin** 2015-07-23 22:26 UTC

**Comment by dimas** [comment] 2015-08-04 14:16
Guys, just to let you know, the Gson you are using returns null for an empty string - https://github.com/google/gson/issues/457

So the NPE will happen whenever server returns an empty body. Sure thing it is a problem on the server side then but a good client is better be prepared for shitty response.
